# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e2da2ea2f0c349e22f21b1e34359053fcf885cf2b65a845309876f01526408b0e4a8a235ec7c6046044f48656589d2fdd5513c7fc6700b9b2e4e0ea5dd86e7d9

test:
  secret_key_base: 2a04d45c4fe82dd7094ecc67a315218f7cb8dde821296b9f586b461cf99fb80b9b72a8c4017718f50721074056e3d7e514fe453e0e3effe3b8f4fe3ff2905b50

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
